import { SITE } from './constants';

export const jsonLd = {
  "@context": "https://schema.org",
  "@type": ["LocalBusiness", "ProfessionalService"],
  name: SITE.name,
  description: "KRAKEN METALS, expert en soudage TIG et MIG, soudage de précision à Ivry-sur-Seine. Métallerie, réparation métallique. Intervention rapide sur Paris et toute l'Île-de-France.",
  image: `${SITE.url}/og-image.jpg`,
  "@id": SITE.url,
  url: SITE.url,
  telephone: SITE.phoneHref.replace("tel:", ""),
  knowsAbout: ["Soudage TIG", "Soudage MIG", "Acier", "Inox", "Aluminium", "Métallerie", "Réparation métallique"],
  address: {
    "@type": "PostalAddress",
    streetAddress: SITE.address,
    addressLocality: "Ivry-sur-Seine",
    postalCode: "94200",
    addressRegion: "Val-de-Marne",
    addressCountry: "FR",
  },
  areaServed: [
    { "@type": "City", "name": "Ivry-sur-Seine" },
    { "@type": "City", "name": "Vitry-sur-Seine" },
    { "@type": "City", "name": "Villejuif" },
    { "@type": "City", "name": "Charenton-le-Pont" },
    { "@type": "City", "name": "Maisons-Alfort" },
    { "@type": "City", "name": "Alfortville" },
    { "@type": "City", "name": "Choisy-le-Roi" },
    { "@type": "City", "name": "Le Kremlin-Bicêtre" },
    { "@type": "City", "name": "Saint-Maurice" },
    { "@type": "Place", "name": "Paris 13" },
    { "@type": "Place", "name": "Paris 12" },
    { "@type": "Place", "name": "Paris 14" },
    { "@type": "City", "name": "Paris" },
    { "@type": "AdministrativeArea", "name": "Val-de-Marne" },
    { "@type": "AdministrativeArea", "name": "Île-de-France" },
  ],
  geo: {
    "@type": "GeoCoordinates",
    latitude: 48.8145,
    longitude: 2.385,
  },
  openingHoursSpecification: [
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
      opens: "09:00",
      closes: "20:00",
    },
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: "Saturday",
      opens: "09:00",
      closes: "20:00",
    },
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: "Sunday",
      opens: "09:00",
      closes: "20:00",
    },
  ],
  priceRange: "€€",
};
